### ISSUE TITLE
Close all projects on startup

### ISSUE THREAD

**Issue by strobaek** [madskristensen/CloseAllTabs#2]
Apart from the current functionality it would be nice if all solution folders and projects were also collapsed upon startup.

**Comment by madskristensen** [comment]
This should have been added already. Can you please verify it works by installing the latest [CI build](http://vsixgallery.com/extension/55640f47-34bc-436b-8820-e7f64fbb31fc/) and enabling it in the settings?

**Comment by strobaek** [comment]
It closes the open files, but not the projects. Can it be because I have them located in (solution) folders?

**Comment by madskristensen** [comment]
Did you enable the collapsing of both projects and solution folders in the settings?

**Comment by strobaek** [comment]
Yes, I did.
I'm on VS Enterprise 2015, 14.0.25424.00 Update 3.
1.3.16 of Clean Solution

**Comment by madskristensen** [comment]
It appear to be an issue with VS when projects are located in solution folders. VS will automatically expand the solution folder if it contain projects when the solution opens. You can try it yourself by clicking the "Collapse all" button on the Solution Explorer toolbar and then close and reopen the solution.
