### ISSUE TITLE
Exception from HRESULT: 0x80041FEB The tab has been closed.

### ISSUE THREAD

**Issue by ghost** [madskristensen/CloseAllTabs#3]
I just installed CloseAllTabs 1.4.20 (Visual Studio 2015 Professional) and disabled all "**Tools > Environment > Clean Solution**" settings except "**General > Delete bin and obj folders**", which is set to "**True**".  Immediately before the solution closes, I'm seeing the following error in the status bar:

`HRESULT: 0x80041FEB The tab has been closed.`

I'm not 100% sure this is CloseAllTabs' fault, but the exception no longer appears if I uninstall the CloseAllTabs extension.  Nor did I ever notice that message until immediately after I installed CloseAllTabs.  The good news is that it doesn't appear to be adversely affecting Visual Studio's usability... anyway, I just thought I'd mention it.

**Comment by ghost** [comment]
Feel free to delete this.  After uninstalling CloseAllTabs, I still see the message when I close Visual Studio with an open solution.  It's probably just something wonky with the shutdown process.

**Comment by James-E-A** [comment]
I have never used this extension, and am still getting this error. Surely unrelated.
