### ISSUE TITLE
Support for closing folder

### ISSUE THREAD

**Issue by Megasware128** [madskristensen/CloseAllTabs#7]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.4.20

### Description
Opening folders is a new feature in Visual Studio 2017. Tabs should also close when closing a folder.

### Steps to recreate
1. Open folder in Visual Studio 2017
2. Open some random files from the folder
3. Close Visual Studio
4. Reopen Visual Studio

### Current behavior
The files are still open.

### Expected behavior
The files should be closed.

**Comment by nhammadi** [comment]
@Megasware128  the feature was implemented in the latest version of Clean Solution (1.4.27). You can use VSIX Gallery - nightly builds extension (also by Mads) to get the latest build of many extensions.
@madskristensen Issue can be closed.
